{% set name = "kcompletion" %}
{% set version = "5.75.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kcompletion-{{ version }}.tar.xz
  sha256: 409b2759b6ac476b16fd6b5efd78381e9a840bae041fef35285404d2b79eeeff

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kcompletion', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - kconfig >={{ version }}
    - kwidgetsaddons >={{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Completion.so

about:
  home: https://api.kde.org/frameworks/kcompletion/html/index.html
  license: BSD-3-Clause AND LGPL-2.0-or-later AND LGPL-2.1-or-later
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-or-later.txt
  summary: Powerful completion framework, including completion-enabled lineedit and combobox.
  description: |
    When typing filenames, email addresses and other text where the user often wants to
    select from existing data (including what they previously typed) rather than enter
    anything wholly original, users often find it helpful if they only need to type the
    first few characters, and then have the application offer them a set of choices or
    attempt to finish off what they were typing. Email clients, shells and "open file"
    dialogs often provide this functionality.

    This framework helps implement this in Qt-based applications. You can use one of
    the completion-ready widgets provided by this framework, or integrate it into your
    application's other widgets directly.
  dev_url: https://cgit.kde.org/kcompletion.git/tree

extra:
  recipe-maintainers:
    - scopatz
