travis:
  secure:
    BINSTAR_TOKEN: q/HmRtdMyOLrRontXRpo8rkRJJQ6cQd/nD8vyVHXR9FGNOPxp43/S/r8U/TpR2RrYG7MDbJEvAks/dNqRyKn+h18H3FXkmCHi7TeP309QE+3pRYSLBcivUKO+6N7CyxHsNPeU3DswwcFkfPSvoSximAUWfI6TkDFHRm+bU/Tp1AI+m6H8Ih32KcENsM/YY5r/EA79MJvcWBzqjfLHw7hdekbXlBxntSoyrJT/AIn2fJuYHa8Lq3i3Uz8r0pvGOCU6uFQop7zKPCvAK1UDoVRClBD9G77kXb49UfSSWx6sLlSZbkKv416h8LSMh0beVYQNM0PFFgTGx5Ejf4M/wmOuMBDY0FOclNVc+rslKBwJn0v9Up+bYRmnCkVqcZCwXXNQMUmIm2Lc710dLj3moCkFCF4zB4qPpERzvO8vX3SaaNx4lQdj2UsT5SCtH/z7HiI5kbDOrhgGgpgIjhcbXXELEit6Tye+ZjRbQJOIAIZeJ74A+oIa3wcfSqE6du7UeEcI/7SEp/ff1UYF5ZRVq4RhbvZDrSLg0ywV78QsrBdHCZBm3a2s3HEHpaS6+IOoQImdcgSY0AjP5iHZSlgvBjOm1rCVyI75lsWoBh1lJ9SSATQN7RuqhsP/zYLtY0tRnJPstv7itFYyHHdDwGNDanPIVf4TeggBZ7p/6767YLkV3U=
conda_forge_output_validation: true
bot:
  check_solvable: True
  
